# Receptive field functions
# N/B. dataset input is in form of e.g. dataset = r"F:\Laura\zebrafish_02_12_2025\Phase_01\4px_20Hz_40mins_shuffle_idx_4"

# %% Function to plot a multipanel figure of each top QI (>20) cell's receptive field, calculated using mean squared error method


def plot_mse_rf_old(dataset, qi_limit):
    # Import dependencies
    import numpy as np
    from pathlib import Path
    import matplotlib.pyplot as plt
    import math

    # Load dataset
    root = Path(dataset)
    # Load quality file
    quality = np.load(root / "quality.npy")

    # Find top cells with quality index > qi limit
    valid_rows_quality = ~np.isnan(quality[:, 0])
    top_cells_idx = np.where(quality[valid_rows_quality, 0] > qi_limit)
    top_cells_idx = np.where(valid_rows_quality)[0][top_cells_idx]
    top_cells = quality[top_cells_idx, 1].astype(int)

    # Choose number of columns and rows in plot
    n_cols = math.ceil(math.sqrt(len(top_cells)))
    n_rows = math.ceil(len(top_cells) / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 20))
    axes = axes.flatten()

    for idx, cell_id in enumerate(top_cells):
        image = np.load(
            root / f"cell_{int(cell_id)}/subset_dev_img.npy"
        )  # Import subset_dev_img.npy for cells with the best QI (cell index) [generated by running the calculate_mse.py]
        # cax = ax[idx].imshow(image, cmap="Greys", vmin = min_value, vmax = max_value) # imshow is used to display data as an image. cmap defines colour scheme
        cax = axes[idx].imshow(image, cmap="Greys", origin="upper")

        # Add 8 µm = 2-pixel scale bar in the top-right corner
        bar_length_px = 2
        x_end = image.shape[1] - 10  # 10 px from right edge
        x_start = x_end - bar_length_px
        y_pos = 10  # 10 px from top
        axes[idx].plot([x_start, x_end], [y_pos, y_pos], color="red", linewidth=3)
        axes[idx].text(
            x_start - 13,
            y_pos + 11,
            "8 µm",
            color="red",
            fontsize=10,
            ha="left",
            va="bottom",
        )  # <-- move text left by increasing this number

        # Set ticks and labels
        axes[idx].set_title(f"Cell {int(cell_id)}")
        axes[idx].set_xticks([0, 50, 100])
        axes[idx].set_yticks([0, 50, 100])
        axes[idx].set_xlabel("pixels")

    fig.suptitle(
        f"Spatial receptive fields for cells with qi >{qi_limit}", fontsize=20, y=0.99
    )
    plt.tight_layout()
    plt.show()


# %% Plot the STA for each of the top QI cells [can help work out what type the cell is e.g. OFF].
# Locates the pixel of spatial noise presented that the cell has peak responsiveness to, and shows what it was doing on average, 60 frames pre and 20 frames post a spike


def plot_STAs_old(dataset):
    # Import dependencies
    import numpy as np
    from pathlib import Path
    import matplotlib.pyplot as plt
    import math

    # Load dataset
    root = Path(dataset)
    # Load quality file
    quality = np.load(root / "quality.npy")

    # Find top cells with quality index > 20
    qi_limit = 20
    valid_rows_quality = ~np.isnan(quality[:, 0])
    top_cells_idx = np.where(quality[valid_rows_quality, 0] > qi_limit)
    top_cells_idx = np.where(valid_rows_quality)[0][top_cells_idx]
    top_cells = quality[top_cells_idx, 1].astype(int)

    # Choose number of columns and rows in plot
    n_cols = math.ceil(math.sqrt(len(top_cells)))
    n_rows = math.ceil(len(top_cells) / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 20))
    axes = axes.flatten()

    for idx, cell_id in enumerate(top_cells):
        kernel = np.load(root / f"cell_{int(cell_id)}\kernel.npy")
        single_channel = kernel[
            :, int(quality[cell_id, 3]), int(quality[cell_id, 2])
        ]  # this selects the coordinates of the spatial noise where the cell has peak responsiveness to
        c_id = int(cell_id)  # convert to integer
        single_channel = kernel[:, int(quality[c_id, 3]), int(quality[c_id, 2])]
        axes[idx].plot(single_channel)
        axes[idx].set_title(f"Cell ID = {int(cell_id)}")
        axes[idx].axvline(x=80, linestyle="--", color="r")
        axes[idx].set_xticks([0, 50, 100])
        axes[idx].set_xticklabels([0, 0.25, 0.5])
        axes[idx].set_xlabel("s")

    fig.suptitle(" STA for cells with qi>20", fontsize=18, y=0.99)
    plt.tight_layout()
    plt.show()


# %% Function to plot a receptive field mosaic for cells with qi index above 20


def plot_contour_mosaic_old(dataset, intensity_threshold, pixel_dimensions):
    # intensity threshold sets intensity threshold of contouring
    # pixel_dimensions is the total number of pixels in x and y coordinates of MEA visual field (800 for 12px noise and 600 for 4px noise)
    # Import dependencies
    import numpy as np
    from pathlib import Path
    import matplotlib.pyplot as plt
    from matplotlib import colormaps
    from skimage import measure

    # Load dataset
    root = Path(dataset)
    # Load quality file
    quality = np.load(root / "quality.npy")

    # Find top cells with quality index > 20
    qi_limit = 20
    valid_rows_quality = ~np.isnan(quality[:, 0])
    top_cells_idx = np.where(quality[valid_rows_quality, 0] > qi_limit)
    top_cells_idx = np.where(valid_rows_quality)[0][top_cells_idx]
    top_cells = quality[top_cells_idx, 1].astype(int)

    colours = (
        (colormaps["tab20"].colors)
        + (colormaps["tab20b"].colors)
        + (colormaps["tab20c"].colors)
    )  # creates a list of 60 colours

    fig, axes = plt.subplots(figsize=(10, 10))

    for idx, cell_id in enumerate(top_cells):
        image = np.load(root / f"cell_{int(cell_id)}/subset_dev_img.npy")

        contours = measure.find_contours(
            image, level=intensity_threshold
        )  # use find_contours from measure from skimage to trace intensity threshold boundary of receptive field

        for i, rf in enumerate(
            contours
        ):  # skimage outputs contours in two columns - first column [0] is y coordinates, second column [1] is x coordinates. So for matplotlib, which takes (x,y) you need to plot [:,1] first.
            # Find cell's RF's actual position (x, y) from quality array
            x_pos = quality[:, 2]
            y_pos = quality[:, 3]
            x_center = x_pos[int(cell_id)]
            y_center = y_pos[int(cell_id)]

            # Shift receptive field coordinates by visual-field location
            rf_x = rf[:, 1] + x_center - image.shape[1] / 2
            rf_y = rf[:, 0] + y_center - image.shape[0] / 2

            axes.fill(
                rf_x,
                rf_y,  # use ax.fill to fill coordinates (do this first, so that then you plot lines on top they are more visible)
                facecolor=colours[idx % len(colours)],
                alpha=0.3,
            )  # set alpha value to be a bit transparent (0 completely transparent, 1 completely opaque)

            axes.plot(
                rf_x,
                rf_y,  # use ax.plot to plot line of coordinates
                linewidth=2,
                color=colours[idx % len(colours)],
            ),  # the % len(colours) means you will cycle through the colour list again if needed
            # label = f'Cell {int(cell_id)}' if i == 0 else "_nolegend_") # only set legend for each cell once

    fig.suptitle(
        f"Spatial receptive fields mosaic\n[cells with qi >{qi_limit}, intensity threshold = {intensity_threshold}]",
        fontsize=18,
    )  # \n creates a new line in the plot title
    axes.invert_yaxis()  # invert axis so that (0,0) is in top left, as it is in images
    axes.set_ylim([0, pixel_dimensions])  # set y and x-axis
    axes.set_xlim([0, pixel_dimensions])
    axes.legend(fontsize=15, loc="upper right")  # add legend
    plt.tight_layout()
    plt.show()


# %% Function to plot a multipanel figure where each of the top QI (>20) cell's receptive fields are plotted.
# Each cell is then overlaid by the receptive field of the most strongly (spatially) overlapping cell.
# Define the number of top overlapping cells to plot by "number of overlaps".


def plot_top_cells_overlay_old(dataset, number_of_overlaps):
    # dataset is e.g.r"F:\Laura\zebrafish_02_12_2025\Phase_01\4px_20Hz_40mins_shuffle_idx_4"
    # number of overlaps is how many cells you want to overlay

    # Import dependencies
    import numpy as np
    from pathlib import Path
    import matplotlib.pyplot as plt
    import math
    import pandas as pd

    # Load dataset
    root = Path(dataset)
    # Load quality file
    quality = np.load(root / "quality.npy")

    # Find top cells with quality index > 20
    qi_limit = 20
    valid_rows_quality = ~np.isnan(quality[:, 0])
    top_cells_idx = np.where(quality[valid_rows_quality, 0] > qi_limit)
    top_cells_idx = np.where(valid_rows_quality)[0][top_cells_idx]
    top_cells = quality[top_cells_idx, 1].astype(int)

    # Set up correct number of subplots
    n_cols = math.ceil(math.sqrt(len(top_cells)))
    n_rows = math.ceil(len(top_cells) / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 20))
    axes = axes.flatten()

    # Loop over each main cell
    for idx, cell_id in enumerate(top_cells):
        image = np.load(
            root / f"cell_{int(cell_id)}/subset_dev_img.npy"
        )  # Load receptive field (mse method)
        axes[idx].imshow(
            image, cmap="Greys", origin="upper"
        )  # plot receptive field for each main cell

        # -----
        # Find the coordinates of the centre of the main cell's receptive field
        x_center = quality[cell_id, 2]
        y_center = quality[cell_id, 3]

        # Initiate overlaps list - to put overlapping cells into
        overlaps = []  # reset overlaps for each new main cell

        # Find overlaps with other top cells
        for other_cell in top_cells:
            if (
                other_cell == cell_id
            ):  # if the "other cell" is actually the "main cell" then ignore and continue
                continue

            other_image = np.load(
                root / f"cell_{other_cell}/subset_dev_img.npy"
            )  # load receptive field of each other cell
            other_x = quality[
                other_cell, 2
            ]  # find coordinates of centre of each other cell's receptive field
            other_y = quality[other_cell, 3]

            diff_x = (
                other_x - x_center
            )  # find the difference in location between main cell and each other cell
            diff_y = other_y - y_center

            y_start = int(max(0, -diff_y))
            y_end = int(min(image.shape[0], other_image.shape[0] - diff_y))
            x_start = int(max(0, -diff_x))
            x_end = int(min(image.shape[1], other_image.shape[1] - diff_x))

            overlap_area = max(0, y_end - y_start) * max(
                0, x_end - x_start
            )  # find extent of overlap between each other cell with the main cell

            if overlap_area > 0:  # append all details to overlaps list
                overlaps.append(
                    {
                        "overlap_area": overlap_area,
                        "cell_id": other_cell,
                        "diff_x": diff_x,
                        "diff_y": diff_y,
                        "y_start": y_start,
                        "y_end": y_end,
                        "x_start": x_start,
                        "x_end": x_end,
                    }
                )

        # Process overlaps after checking all other cells
        if overlaps:
            overlaps_df = pd.DataFrame(overlaps)  # convert to pandas df
            sorted_overlaps = overlaps_df.sort_values(
                "overlap_area", ascending=False
            ).reset_index(
                drop=True
            )  # sort by overlap area in descending order & reset index of rows (important)

            # Overlay top N cells (defined by number of overlaps)
            for i in range(
                min(number_of_overlaps, len(sorted_overlaps))
            ):  # deals with the fact you may request to overlay more cells than actually overlap a main cell
                overlay_id = sorted_overlaps["cell_id"].iloc[
                    i
                ]  # find the cell id of the overlapping cells
                overlay_image = np.load(
                    root / f"cell_{overlay_id}/subset_dev_img.npy"
                )  # load the receptive field of the overlapping cell

                draw_x0 = max(
                    0, sorted_overlaps["diff_x"].iloc[i]
                )  # determine where to plot the overlapping cell onto the main cell
                draw_y0 = max(0, sorted_overlaps["diff_y"].iloc[i])
                draw_x1 = draw_x0 + (
                    sorted_overlaps["x_end"].iloc[i]
                    - sorted_overlaps["x_start"].iloc[i]
                )
                draw_y1 = draw_y0 + (
                    sorted_overlaps["y_end"].iloc[i]
                    - sorted_overlaps["y_start"].iloc[i]
                )

                axes[idx].imshow(  # plot the overlapping cell in red, and transparent
                    overlay_image[
                        sorted_overlaps["y_start"]
                        .iloc[i] : sorted_overlaps["y_end"]
                        .iloc[i],
                        sorted_overlaps["x_start"]
                        .iloc[i] : sorted_overlaps["x_end"]
                        .iloc[i],
                    ],
                    cmap="Reds",
                    alpha=0.3,
                    origin="upper",
                    extent=[draw_x0, draw_x1, draw_y1, draw_y0],
                )

            # Build title list of top overlapping cells to put in brackets
            top_overlap_ids = (
                sorted_overlaps["cell_id"].iloc[:number_of_overlaps].tolist()
            )
        else:
            top_overlap_ids = []

        # Set the subplot title: "Cell X (Y, Z, ...)"
        if top_overlap_ids:
            title_str = f"Cell {int(cell_id)} ({', '.join(map(str, top_overlap_ids))})"
        else:
            title_str = f"Cell {int(cell_id)}"
        axes[idx].set_title(title_str)

        # Add scale bar to each subplot: 8 µm = 2 pixels
        bar_length_px = 2
        x_end_bar = image.shape[1] - 10
        x_start_bar = x_end_bar - bar_length_px
        y_pos = 10
        axes[idx].plot(
            [x_start_bar, x_end_bar], [y_pos, y_pos], color="red", linewidth=3
        )
        axes[idx].text(x_start_bar - 13, y_pos + 11, "8 µm", color="red", fontsize=10)

        # Set ticks and labels
        axes[idx].set_xticks([0, 50, 100])
        axes[idx].set_yticks([0, 50, 100])
        axes[idx].set_xticklabels([0, 200, 400])
        axes[idx].set_yticklabels([0, 200, 400])
        axes[idx].set_xlabel("µm")

    # Set figure title
    fig.suptitle(
        f"Spatial receptive fields for cells with qi > 20, with top {number_of_overlaps} overlapping cells",
        fontsize=20,
        y=0.99,
    )
    plt.tight_layout()
    plt.show()


# %% Function to extract statistics from receptive fields (calculated using MES method)
# Should return 4 plots: multipanel plot with statistics marked, then histogram of diameter and sphericity, and polar plot of orientation


def plot_rf_statistics_old(dataset, sd_threshold, qi_limit):
    # sd_threshold is number of standard deviations away from max pixel intensity, that intensity threshold will be set to

    # Import dependencies
    import numpy as np
    from pathlib import Path
    from skimage import measure
    from skimage.draw import polygon2mask
    from scipy.spatial.distance import pdist, squareform
    from tqdm import tqdm
    import pandas as pd
    import matplotlib.pyplot as plt
    import math
    from numpy.linalg import eigh

    # Load dataset
    root = Path(dataset)
    # Load quality file
    quality = np.load(root / "quality.npy")

    # Find top cells with quality index > 20
    valid_rows_quality = ~np.isnan(quality[:, 0])
    top_cells_idx = np.where(quality[valid_rows_quality, 0] > qi_limit)
    top_cells_idx = np.where(valid_rows_quality)[0][top_cells_idx]
    top_cells = quality[top_cells_idx, 1].astype(int)

    # For loop to extract all the receptive field statistics
    rf_statistics_list = []
    pixel_size = 4  # pixel size in micrometres (4 micrometres)

    for idx, cell_id in enumerate(tqdm(top_cells)):
        # Import receptive field image, calculated using mean error squared method
        image = np.load(root / f"cell_{int(cell_id)}/subset_dev_img.npy")

        # Calculate intensity threshold
        max_intensity = np.max(image)  # calculate max intensity pixel
        std_intensity = np.std(image)  # calculate standard deviation of pixel intensity
        intensity_threshold = (
            max_intensity - sd_threshold * std_intensity
        )  # set intensity threshold

        # Find contour of receptive field (i.e. line around the edge of the rf, defined by the intensity threshold)
        contours = measure.find_contours(
            image, level=intensity_threshold
        )  # use find_contours from measure from skimage
        contour = max(contours, key=len)  # choose the longest contour for each rf
        rf_y, rf_x = (
            contour[:, 0],
            contour[:, 1],
        )  # row -> y, col -> x (for plotting later on)
        mask = polygon2mask(
            image.shape, contour
        )  # convert contour coordinates (row, col) to (y, x)
        area_pixels = mask.sum()  # count pixels in total area of rf

        # Find max diameter of receptive field
        yx_coords = np.argwhere(mask)  # Get coordinates of all pixels inside RF

        # --- GUARD AGAINST DEGENERATE RFs ---
        if yx_coords.shape[0] < 2:
            continue

        D = squareform(
            pdist(yx_coords)
        )  # calculate distance matrix between coordinates
        i, j = np.unravel_index(
            np.argmax(D), D.shape
        )  # find coordinates which are furthest apart
        max_diameter = D[
            i, j
        ]  # Compute maximum diameter (largest distance between any two pixels)
        coord_a = tuple(yx_coords[i])
        coord_b = tuple(yx_coords[j])
        y1, x1 = coord_a
        y2, x2 = coord_b

        # Calculate circularity index for each receptive field (4pi*Area/perimeter)
        perimeter_pixels = len(
            contour
        )  # Approximate length of perimeter of rf in pixels
        circularity_index = 4 * np.pi * area_pixels / (perimeter_pixels**2)

        # Compute orientation using PCA --- (selects orientation with greatest variation along it) - think about / understand more - can you create a covariance matrix of
        coords_centered = yx_coords - yx_coords.mean(
            axis=0
        )  # subtracts centre - so we can describes variance relative to centre
        cov = np.cov(coords_centered, rowvar=False)  # covariance matrix
        eigvals, eigvecs = eigh(
            cov
        )  # extract values of variance along axes, and the orientation of those axes
        long_axis_vec = eigvecs[:, np.argmax(eigvals)]  # extract largest eigen value
        angle_rad = np.arctan2(long_axis_vec[0], long_axis_vec[1])  # converts to angle
        orientation_deg = np.degrees(angle_rad) % 180

        # Set major orientation line for plotting
        center = yx_coords.mean(axis=0)
        half_length = max_diameter / 2
        # vector along major axis scaled by half the max diameter
        dy, dx = long_axis_vec * half_length
        y_major = [center[0] - dy, center[0] + dy]
        x_major = [center[1] - dx, center[1] + dx]

        # Add receptive field statistics to table
        rf_statistics_list.append(
            {
                "cell_id": cell_id,
                "area_pixels": area_pixels,
                "max_diameter_pixels": max_diameter,
                "max_diameter_um": max_diameter * pixel_size,
                "circularity_index": circularity_index,
                "orientation_degree": orientation_deg,
                "rf_y": rf_y,
                "rf_x": rf_x,
                "y_major": y_major,
                "x_major": x_major,
                "y1": y1,
                "y2": y2,
                "x1": x1,
                "x2": x2,
            }
        )

    rf_statistics_table = pd.DataFrame(rf_statistics_list)

    # Now plot the receptive fields, with the perimeter line, max diameter, and orientation degree - ordered by circularity index

    # Sort rf_statistics_table by descending circularity index
    rf_statistics_table_sorted = rf_statistics_table.sort_values(
        by="circularity_index", ascending=False
    )
    sorted_cells = rf_statistics_table_sorted["cell_id"]

    # Set number of columns and rows in plot
    n_cols = math.ceil(math.sqrt(len(sorted_cells)))
    n_rows = math.ceil(len(sorted_cells) / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 20))
    axes = axes.flatten()
    handles = []

    for idx, cell_id in enumerate(tqdm(sorted_cells)):
        image = np.load(root / f"cell_{int(cell_id)}/subset_dev_img.npy")
        circ_idx = rf_statistics_table.loc[
            rf_statistics_table["cell_id"] == cell_id, "circularity_index"
        ].values[0]
        orientation_deg = rf_statistics_table.loc[
            rf_statistics_table["cell_id"] == cell_id, "orientation_degree"
        ].values[0]
        axes[idx].imshow(image, cmap="Greys", origin="upper")

        if idx == 0:
            (h1,) = axes[idx].plot(
                rf_statistics_table_sorted["rf_x"].iloc[idx],
                rf_statistics_table_sorted["rf_y"].iloc[idx],
                color="red",
                linewidth=2,
                label="Perimeter",
            )
            (h2,) = axes[idx].plot(
                [
                    rf_statistics_table_sorted["x1"].iloc[idx],
                    rf_statistics_table_sorted["x2"].iloc[idx],
                ],
                [
                    rf_statistics_table_sorted["y1"].iloc[idx],
                    rf_statistics_table_sorted["y2"].iloc[idx],
                ],
                color="cyan",
                linewidth=2,
                label="Max diameter",
            )
            (h3,) = axes[idx].plot(
                rf_statistics_table_sorted["x_major"].iloc[idx],
                rf_statistics_table_sorted["y_major"].iloc[idx],
                color="yellow",
                linewidth=2,
                label="Orientation",
            )
            handles = [h1, h2, h3]
        else:
            axes[idx].plot(
                rf_statistics_table_sorted["rf_x"].iloc[idx],
                rf_statistics_table_sorted["rf_y"].iloc[idx],
                color="red",
                linewidth=2,
            )
            axes[idx].plot(
                [
                    rf_statistics_table_sorted["x1"].iloc[idx],
                    rf_statistics_table_sorted["x2"].iloc[idx],
                ],
                [
                    rf_statistics_table_sorted["y1"].iloc[idx],
                    rf_statistics_table_sorted["y2"].iloc[idx],
                ],
                color="cyan",
                linewidth=2,
            )
            axes[idx].plot(
                rf_statistics_table_sorted["x_major"].iloc[idx],
                rf_statistics_table_sorted["y_major"].iloc[idx],
                color="yellow",
                linewidth=2,
            )

        axes[idx].set_title(
            f"Cell {int(cell_id)}, CI({circ_idx:.2f}), OD({orientation_deg:.1f})",
            fontsize=10,
        )
        axes[idx].set_xticks([0, 50])
        axes[idx].set_yticks([0, 50])

    # Turn off any unused subplots
    for ax_idx in range(len(top_cells), len(axes)):
        axes[ax_idx].axis("off")

    # Add a single legend for the entire figure in the bottom-right corner
    fig.legend(handles=handles, loc="lower right", fontsize=12)

    fig.suptitle(
        f"Spatial receptive fields for cells with qi > 20, with contour outline (+ {sd_threshold} SD of max intensity)",
        fontsize=20,
        y=0.99,
    )
    plt.tight_layout()
    plt.show()

    # Extra plots

    # plot histogram of diameter sizes
    plt.figure(figsize=(5, 5))
    plt.hist(rf_statistics_table["max_diameter_um"])
    plt.ylabel("number of cells")
    plt.xlabel("max diameter of rf (um)")
    plt.title("receptive field size")
    plt.show()

    # plot histogram of circularity index
    plt.figure(figsize=(5, 5))
    plt.hist(rf_statistics_table["circularity_index"])
    plt.ylabel("number of cells")
    plt.xlabel("circularity_index")
    plt.title("receptive field circularity index")
    plt.show()

    # Plot polar histogram of cell orientations (5° bins) (AI written)
    orientations = rf_statistics_table[
        "orientation_degree"
    ].values  # Get orientation degrees
    circularity = rf_statistics_table[
        "circularity_index"
    ].values  # Get circularity index
    bins_deg = np.arange(0, 180, 10)  # Define bins (10° bins from 0 to 180)
    hist_counts, bin_edges = np.histogram(
        orientations, bins=bins_deg, weights=circularity
    )

    # Compute bin centers in radians for polar plot
    bin_centers_deg = (bin_edges[:-1] + bin_edges[1:]) / 2
    bin_centers_rad = np.deg2rad(bin_centers_deg)

    # Create half-polar plot
    fig = plt.figure(figsize=(5, 6))
    ax = fig.add_subplot(111, polar=True)
    ax.set_theta_zero_location("N")  # 0° at the top
    ax.set_theta_direction(-1)  # clockwise

    # Plot bars
    ax.bar(
        bin_centers_rad,
        hist_counts,
        width=np.deg2rad(10),
        bottom=0.0,
        edgecolor="red",
        color="peachpuff",
        align="center",
    )

    # Set limits for half-circle (0 to 180°)
    ax.set_thetamin(0)
    ax.set_thetamax(180)
    ax.set_title("Receptive field orientations", fontsize=14, pad=20)
    plt.show()


# %% Function to use covariance matrix to plot centre surround receptive field structure
def plot_centre_surrounds_old(dataset, qi_limit):
    # Import dependencies
    import numpy as np
    from pathlib import Path
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    from matplotlib_scalebar.scalebar import ScaleBar
    import datashader as ds
    import datashader.transfer_functions as tf
    import xarray as xr
    from colorcet import coolwarm
    from smoothing.gaussian import smooth_ker
    from location.channel_handling import masking_square
    from covariance.filtering import cov_filtering_sum
    from mpl_toolkits.axes_grid1 import make_axes_locatable
    from tqdm import tqdm

    # Load dataset
    root = Path(dataset)
    # Load quality file
    quality = np.load(root / "quality.npy")

    # Find top cells with quality index > 20
    valid_rows_quality = ~np.isnan(quality[:, 0])
    top_cells_idx = np.where(quality[valid_rows_quality, 0] > qi_limit)
    top_cells_idx = np.where(valid_rows_quality)[0][top_cells_idx]
    top_cells = quality[top_cells_idx, 1].astype(int)

    # Define global variables
    cut = 150
    half_cut = cut // 2
    pixel_size = 4  # micrometres

    # Create plotting grid first
    n_cells = len(top_cells)
    n_cols = 8
    n_rows = int(np.ceil(n_cells / n_cols))

    fig, axs = plt.subplots(n_rows, n_cols, figsize=(20, 20))
    axs = np.atleast_2d(axs)

    # %% Loop through cells and plot immediately
    # Load data, do illumination correction, generate extended array to prevent edge effects, calculate covariance matrix for each cell
    for plot_idx, cell_id in enumerate(
        tqdm(top_cells)
    ):  # can use tqdm to wrap for loop to create progress bar. # For the top cells
        ax = axs[plot_idx // n_cols, plot_idx % n_cols]

        # Load data
        sta_path = (
            root / f"cell_{cell_id}/kernel.npy"
        )  # define the file path to the STA
        sta_data = np.load(sta_path)  # load the STA for cell i as sta_data

        ker_sm = smooth_ker(
            sta_data
        )  # smooth the STA for cell i using the smooth_ker function
        original_shape = (
            sta_data.shape
        )  # calculate the variance of the value of each pixel in the STA across time
        T, H, W = original_shape  # extract the dimensions of the original STA

        # Illumination correction
        data_flat = sta_data.reshape(T, H * W).astype(
            float
        )  # flatten the sta data so that it goes from T,H,W to T,H*W (where T is time/frames)

        sum_img = (
            np.sum(data_flat, axis=0) / 100
        )  # calculate the sum brightness of every pixel across time
        median_sum = np.median(sum_img)  # find the median brightness of pixels
        correction = (
            sum_img - median_sum
        )  # calculate the correction required by each pixel to obtain median brightness

        data_flat -= correction  # correct each pixel for each time frame

        sta_data = data_flat.reshape(
            T, H, W
        )  # reshape corrected sta data back to original 3D shape
        del data_flat  # delete to free up space

        # Create extended sta array where you add cut (defined at start as 150 pixels) onto each dimension, and fill all the pixels with the median value of the array.
        sta_ext = np.full(
            (T, H + cut, W + cut), np.median(sta_data), float
        )  # AND convert to float (numbers that can have a decimal point)
        ker_ext = np.full(
            (T, H + cut, W + cut), np.median(ker_sm), float
        )  # Do the same as above but for the smoothed data

        # place the real STA into the centre of the extended sta array created above
        sta_ext[:, half_cut:-half_cut, half_cut:-half_cut] = sta_data
        ker_ext[:, half_cut:-half_cut, half_cut:-half_cut] = ker_sm
        del sta_data, ker_sm  # delete the temporary arrays

        # redefine original arrays with the extended versions
        sta_data = sta_ext
        ker_sm = ker_ext
        del sta_ext, ker_ext  # delete the temporary arrays

        T, Hext, Wext = sta_data.shape  # calculate the shape of the new extended arrays

        # Find the pixel which has the maximum variance across time - this will become the centre of the RF
        _, cY, cX = np.unravel_index(np.argmax(np.var(ker_sm, axis=0)), ker_sm.shape)

        # Bound check (# shift the centre of the STA in case the window is too close to the edge?)
        cY = np.clip(cY, half_cut, Hext - half_cut)
        cX = np.clip(cX, half_cut, Wext - half_cut)

        # Create a square mask of dimensions of the STA, with TRUE values of dimensions cut x cut, centred on cX, cY.
        mask = masking_square(Hext, Wext, (cX, cY), cut, cut)
        subset_flat = sta_data[
            :, mask
        ]  # take subset of the STA that is in the masked region
        subset_flat[subset_flat == 0] = np.median(
            subset_flat
        )  # replace any zero values with median pixel value
        subset = subset_flat.reshape(T, cut, cut)  # reshape into 3D shape
        del subset_flat

        # Use cov_filtering_sum function to calculate covariance matrix of the subset of the STA, and return the important pixels and the cm
        important_pixels, cm = cov_filtering_sum(subset, (cut, cut))
        mpi = np.unravel_index(np.argmax(cm), cm.shape)
        cm_subset = cm[mpi[0], :].reshape(
            cut, cut
        )  # extract all covariance values of most important pixel

        # Plot immediately
        # Plot the sum of covariance matrix for the important pixels
        # Plot the mean as a grid of images
        x = y = np.arange(0, cut)  # Create xarray DataArray
        cm_xarr = xr.DataArray(cm_subset, coords=[("x", x), ("y", y)])
        max_cm = np.max(np.abs(cm_subset))

        # Datashader raster
        cvs = ds.Canvas(plot_width=599, plot_height=599)
        shade = tf.shade(
            cvs.raster(cm_xarr, interpolate="nearest", agg="max"),
            how="linear",
            cmap=coolwarm,
            span=(-max_cm, max_cm),
        )
        img = shade.to_pil()

        ax.imshow(img, origin="lower")

        # Colorbar
        divider = make_axes_locatable(ax)
        cax = divider.append_axes("right", size="5%", pad=0.05)
        norm = mpl.colors.Normalize(vmin=-max_cm, vmax=max_cm)
        sm = mpl.cm.ScalarMappable(norm=norm, cmap="coolwarm")
        fig.colorbar(sm, cax=cax, orientation="vertical", ticks=[-max_cm, 0, max_cm])

        # Scalebar + title
        ax.add_artist(ScaleBar(pixel_size, "um", fixed_value=100))
        ax.set_title(f"Cell ID = {int(cell_id)}")

        # Free memory BEFORE next cell
        # del subset, cm, cm_subset, ker_sm, sta_data
        del subset, cm, ker_sm, sta_data
    # Hide empty subplots
    for j in range(plot_idx + 1, n_rows * n_cols):
        axs[j // n_cols, j % n_cols].axis("off")

    fig.suptitle("Spatial receptive fields for cells with qi > 20", fontsize=20, y=0.99)
    fig.tight_layout()
    plt.show()


# %%
